### ISSUE TITLE
Fix CameraControl mousemove on doc for absolute canvas with margins

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#535]
PR https://github.com/xeokit/xeokit-sdk/pull/527 introduces a glitch 

- click-drag-orbit suddenly jumps the camera rotation
- when followPointer is enabled, camera does not dolly to correct mouse position
- only happens when the canvas has space to the left and/or top
- does not happen when canvas is full-screen, or aligned to top-left

![Peek 2021-01-17 18-40](https://user-images.githubusercontent.com/83100/104851194-e5c32200-58f3-11eb-9ad5-f93580e63be9.gif)

Run this here: https://xeokit.github.io/xeokit-sdk/examples/CameraControl_orbit_Duplex_smallCanvas.html

In this example, the canvas CSS is:

````css
#myCanvas {
    position: absolute;
    width: 550px;
    height: 550px;
    left: 150px;
    top: 150px;
}
````
